import type { Metadata, Viewport } from 'next'
// import { Inter } from 'next/font/google'
import './globals.css'
// import Header from '@/src/components/tests/header'
import Head from 'next/head'
import Main from '../src/components/Layout/Main'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: process.env.APP_NAME,
	description: 'Generated by create next app',
}

export const viewport: Viewport = {
	width: 'device-width',
	initialScale: 1,
	maximumScale: 1,
	userScalable: false,
	themeColor: [
		//   { media: '(prefers-color-scheme: light)', color: 'white' },
		//   { media: '(prefers-color-scheme: dark)', color: 'black' },
	],
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const musicKitVersion = `v${process.env.MUSICKIT_VERSION || 1}`
	return (
		<html lang="en" suppressHydrationWarning>
			<Head>
				<meta
					property="og:title"
					content={String(metadata.title)}
					key="title"
				/>
			</Head>
			{/* <body className={inter.className}> */}
			<body className={''}>
				<Main>{children}</Main>
				<script
					// src="https://js-cdn.music.apple.com/musickit/v1/musickit.js"
					src={`https://js-cdn.music.apple.com/musickit/${musicKitVersion}/musickit.js`}
					defer
				></script>
			</body>
		</html>
	)
}
