import type { Metadata, Viewport } from 'next'
import './globals.css'
import Head from 'next/head'

export const metadata: Metadata = {
	title: process.env.APP_NAME,
	description: 'Generated by create next app',
}

export const viewport: Viewport = {
	width: 'device-width',
	initialScale: 1,
	maximumScale: 1,
	userScalable: false,
	themeColor: [
		{ media: '(prefers-color-scheme: light)', color: 'white' },
		{ media: '(prefers-color-scheme: dark)', color: 'black' },
	],
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const musicKitVersion = `v${process.env.MUSICKIT_VERSION || 1}`
	return (
		<html lang="en" suppressHydrationWarning>
			<Head>
				<meta
					property="og:title"
					content={String(metadata.title)}
					key="title"
				/>
			</Head>
			<body className={''}>
				{children}
				<script
					// src="https://js-cdn.music.apple.com/musickit/v1/musickit.js"
					src={`https://js-cdn.music.apple.com/musickit/${musicKitVersion}/musickit.js`}
					defer
				></script>
			</body>
		</html>
	)
}
