import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
// import Header from '@/src/components/tests/header'
import Head from 'next/head'
import Main from './_main'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Yoooo',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<Head>
				<meta
					property="og:title"
					content={String(metadata.title)}
					key="title"
				/>
			</Head>
			<body className={inter.className}>
				<Main>{children}</Main>
				<script
					src="https://js-cdn.music.apple.com/musickit/v1/musickit.js"
					defer
				></script>
			</body>
		</html>
	)
}
